apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-static
spec:
  capacity:
     storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  storageClassName: "" #should be empty for static PV
  perpersistentVolumeReclaimPolicy: Retain
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-e8abcd12:/k8s-roboshop   
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-static
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: "" # Empty string must be explicitly set otherwise default StorageClass will be set  
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
labels:
  purpose: efs-static  
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: nginx-html
      mountPath: /usr/share/nginx/html
    nodeSelector:
     topology.kubernetes.io/zone: us-east-1b  
  volumes:
  - name: nginx-html
    persistentVolumeClaim:
      claimName: efs-static      