apiVersion: v1
kind: pod
metadata:
   name: nginx
   namespace: roboshop
labels:
  name: nginx
  project: roboshop   
spec:
 - name: nginx
   image: nginx
ports:
 - containerPort: 80  #default port for nginx