apiVersion: v1
kind: pod
metadata:
    name: nmulti-container
labels:
 purpose: multi-container
spec:
  containers:
   - name: nginx
     image: nginx
   - name: almalinux
     image: almalinux
     command: ["sleep",  "1000"]
