apiversion: v1
kind: servives
metadata:
   name: nginx-headless
labels:
  app: nginx
  purpose: statefull-demo
spec:
  ports:
   - port: 80
     name: web
  clusterip: None
  selector:
    app: nginx
    purpose: statefull-demo
---
apiversion: v1
kind: servives
metadata:
   name: nginx
labels:
  app: nginx
  purpose: statefull-demo
spec:
  ports:
   - port: 80
     name: web
  selector:
    app: nginx   
    purpose: statefull-demo
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web
spec:
  selector:
    matchLabels:
      app: nginx
      purpose: statefull-demo
  serviceName: "nginx-headless"
  replicas: 3 # by default is 1
  template:
    metadata:
      labels:
        app: nginx # has to match .spec.selector.matchLabels
        purpose: statefull-demo
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - name: www
          mountPath: /usr/share/nginx/html
  #This is PVC
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "roboshop-ebs"
      resources:
        requests:
          storage: 1Gi    
